/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.*; 
import java.awt.*; 
import java.awt.event.*;
import javax.swing.table.*;

/**
 *
 * @author Lenovo
 */
public final class ManageObat extends javax.swing.JFrame {

    /**
     * Creates new form ManageObat
     */
    public ManageObat() {
        initComponents();
        reset();
        load_table();
        this.setLocationRelativeTo(null);
    }
    
    private String id_obat="";
    private String nama_obat="";
    private String harga_obat="";
    private String stok_obat="";
    private String status_crud="";
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_Image = new javax.swing.JLabel();
        txthargao = new javax.swing.JTextField();
        txtstoko = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtido = new javax.swing.JTextField();
        txtnamao = new javax.swing.JTextField();
        btnsimpan = new javax.swing.JButton();
        btnbatal = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        btntambah = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelobat = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_Image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/obat.jpeg"))); // NOI18N
        jPanel1.add(jLabel_Image, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        txthargao.setEnabled(false);
        txthargao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txthargaoKeyReleased(evt);
            }
        });
        jPanel1.add(txthargao, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 87, 263, 35));

        txtstoko.setEnabled(false);
        txtstoko.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtstokoKeyReleased(evt);
            }
        });
        jPanel1.add(txtstoko, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 140, 263, -1));

        jLabel1.setText("ID Obat");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 14, -1, -1));

        jLabel2.setText("Nama Obat");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 52, -1, -1));

        jLabel3.setText("Harga Obat");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 87, -1, -1));

        jLabel4.setText("Stok Obat");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 143, -1, -1));

        txtido.setEnabled(false);
        txtido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtidoKeyReleased(evt);
            }
        });
        jPanel1.add(txtido, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 11, 263, -1));

        txtnamao.setEnabled(false);
        txtnamao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnamaoKeyReleased(evt);
            }
        });
        jPanel1.add(txtnamao, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 49, 263, -1));

        btnsimpan.setText("Simpan");
        btnsimpan.setEnabled(false);
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });
        jPanel1.add(btnsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(704, 11, 123, 48));

        btnbatal.setText("Batal");
        btnbatal.setEnabled(false);
        jPanel1.add(btnbatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(704, 97, 123, 48));

        btndelete.setText("Delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(521, 181, 123, 48));

        btnreset.setText("Reset");
        btnreset.setEnabled(false);
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });
        jPanel1.add(btnreset, new org.netbeans.lib.awtextra.AbsoluteConstraints(704, 181, 123, 48));

        btnedit.setText("Edit");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });
        jPanel1.add(btnedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 181, 123, 48));

        btntambah.setText("Tambah");
        btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahActionPerformed(evt);
            }
        });
        jPanel1.add(btntambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 183, 123, 45));

        jLabel5.setBackground(new java.awt.Color(204, 204, 204));
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 246, -1, -1));

        tabelobat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabelobat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelobatMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelobat);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 909, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        public void setIDO(String v) {
     id_obat = v;
    }
    public void setNamaO(String v) {
     nama_obat = v;
    }
    public void setHargaO(String v) {
     harga_obat = v;
    }
    public void setStokO(String v) {
     stok_obat = v;
    }
    public void setStatusC(String v) {
     status_crud = v;
    }
    public String getIDO() {
     return id_obat;
    }
    public String getNamaO() {
     return nama_obat;
    }
    public String getHargaO() {
     return harga_obat;
    }
    public String getStokO() {
     return stok_obat;
    }  
    public String getStatusC() {
     return status_crud;
    }
    public void load_table(){
        //menampilkan data database kedalam tabel
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID Obat");
        model.addColumn("Nama Obat");
        model.addColumn("Harga Obat");
        model.addColumn("Stok Obat");
        try {
            int no=1;
            String sql = "SELECT * FROM tabel_obat";
            java.sql.Connection conn=(Connection)Koneksi.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                model.addRow(new Object[]{
                res.getString(1),res.getString(2),res.getString(3),res.getString(4)
            });
            }
            tabelobat.setModel(model);
        } catch (SQLException e) {}
}
     public void batal() {
     txtido.setEnabled(false);
     txtnamao.setEnabled(false);
     txthargao.setEnabled(false);
     txtstoko.setEnabled(false);
     btnreset.setEnabled(false);
     btnbatal.setEnabled(false);
     btnsimpan.setEnabled(false);
     btndelete.setEnabled(true);
     btnedit.setEnabled(true);
     btntambah.setEnabled(true);
     setStatusC("");
     reset();
    }
    public void reset(){
    txtido.setText(null);
    txtnamao.setText(null);
    txthargao.setText(null);
    txtstoko.setText(null);

}
     private void enable_all_TF(){
    txtido.setEnabled(true);
    txtnamao.setEnabled(true);
    txthargao.setEnabled(true);
    txtstoko.setEnabled(true);
  

}
     public void insertData() {
     try {
      String sql = "INSERT INTO tabel_obat VALUES ('"+txtido.getText()+"','"+txtnamao.getText()+"','"+txthargao.getText()+"','"+txtstoko.getText()+"')";
      java.sql.Connection conn = Koneksi.configDB();
      java.sql.PreparedStatement pst = conn.prepareStatement(sql);
      pst.execute();
      JOptionPane.showMessageDialog(null, "Penyimpanan Data Berhasil");
      batal();
     } catch (Exception e) {
      JOptionPane.showMessageDialog(this, e.getMessage());
     }
    }
     
      public void updateData() {
     try {
      String sql = "UPDATE tabel_obat SET nama_obat = '"+txtnamao.getText()+ "',harga_obat = '"+txthargao.getText()+"',stok_obat = '"+txtstoko.getText()+ "' WHERE id_obat = '"+txtido.getText()+ "'";
      java.sql.Connection conn = Koneksi.configDB();
      java.sql.PreparedStatement pst = conn.prepareStatement(sql);
      pst.execute();
      JOptionPane.showMessageDialog(null, "data berhasil di edit");
     } catch (Exception e) {
      JOptionPane.showMessageDialog(null, "Perubahan Data Gagal" + e.getMessage());
     }
    }
      
     public void deleteData() {
     try {
      String sql = "DELETE FROM tabel_obat where id_obat='"+txtido.getText()+"'";
      java.sql.Connection conn = Koneksi.configDB();
      java.sql.PreparedStatement pst = conn.prepareStatement(sql);
      pst.execute();
      JOptionPane.showMessageDialog(this, "berhasil di hapus");
     } catch (Exception e) {
      JOptionPane.showMessageDialog(this, e.getMessage());
     }
    }
      public boolean verifikasiData(){
        if(getNamaO() == ""){
            JOptionPane.showMessageDialog(this, "Nama Obat Masih Kosong");
            return false;
        }else if(getHargaO() == ""){
            JOptionPane.showMessageDialog(this, "Harga Obat Masih Kosong");
            return false;
        }else if(getStokO() == ""){
            JOptionPane.showMessageDialog(this, "Stok Obat Masih Kosong");
            return false;
        }else{
            return true;
        }
    }
    
    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        JOptionPane.showMessageDialog(null, "Silahkan Klik Data Yang Ingin Dihapus Pada Tabel Dibawah, dan klik Delete Data");
        btntambah.setEnabled(false);
        btnedit.setEnabled(false);
        btndelete.setEnabled(false);
        btnreset.setEnabled(true);
        btnbatal.setEnabled(true);
        btnsimpan.setEnabled(true);
        btnsimpan.setText("Delete Data");
        txtido.setEnabled(false);
        setStatusC("hapus");
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
        btntambah.setEnabled(false);
        btnedit.setEnabled(false);
        btndelete.setEnabled(false);
        btnsimpan.setEnabled(true);
        btnreset.setEnabled(true);
        btnbatal.setEnabled(true);
        enable_all_TF();
        setStatusC("tambah");
        
    }//GEN-LAST:event_btntambahActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        JOptionPane.showMessageDialog(null, "Silahkan Klik Data Yang Ingin Diedit Pada Tabel Dibawah");
        btntambah.setEnabled(false);
        btnedit.setEnabled(false);
        btndelete.setEnabled(false);
        btnreset.setEnabled(true);
        btnbatal.setEnabled(true);
        btnsimpan.setEnabled(true);
        enable_all_TF();
        txtido.setEnabled(false);
        setStatusC("edit");
    }//GEN-LAST:event_btneditActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnresetActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
       if (getStatusC() == "tambah") {
            if(verifikasiData() == true){
                insertData();
                load_table();
                batal();
            }
        } else if (getStatusC() == "edit") {
                updateData(); 
                load_table();
                batal();
            
        } else if (getStatusC() == "hapus") {
                deleteData();  
                load_table();
                batal();
            
        }
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void txtidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidoKeyReleased
        setIDO(txtido.getText());
    }//GEN-LAST:event_txtidoKeyReleased

    private void txtnamaoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnamaoKeyReleased
        setNamaO(txtnamao.getText());
    }//GEN-LAST:event_txtnamaoKeyReleased

    private void txthargaoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txthargaoKeyReleased
        setHargaO(txthargao.getText());
    }//GEN-LAST:event_txthargaoKeyReleased

    private void txtstokoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtstokoKeyReleased
        setStokO(txtstoko.getText());
    }//GEN-LAST:event_txtstokoKeyReleased

    private void tabelobatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelobatMouseClicked
        if(getStatusC() == "edit" || getStatusC() == "hapus"){
        int baris = tabelobat.rowAtPoint(evt.getPoint());
        String id_obat =tabelobat.getValueAt(baris, 0).toString();
        txtido.setText(id_obat);
        String nama_obat =tabelobat.getValueAt(baris, 1).toString();
        txtnamao.setText(nama_obat);
        String harga_obat = tabelobat.getValueAt(baris, 2).toString();
        txthargao.setText(harga_obat);
        String stok_obat=tabelobat.getValueAt(baris, 3).toString();
        txtstoko.setText(stok_obat);
        }
    }//GEN-LAST:event_tabelobatMouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {                                     
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageObat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageObat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageObat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageObat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageObat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbatal;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnreset;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JButton btntambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel_Image;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelobat;
    private javax.swing.JTextField txthargao;
    private javax.swing.JTextField txtido;
    private javax.swing.JTextField txtnamao;
    private javax.swing.JTextField txtstoko;
    // End of variables declaration//GEN-END:variables
}
