/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.*; 
import java.awt.*; 
import java.awt.event.*;
import javax.swing.table.*;
public class ManageDokter extends javax.swing.JFrame {

    /**
     * Creates new form ManagePasien
     */
    public ManageDokter() {
        initComponents();
        reset();
        load_table();
        this.setLocationRelativeTo(null);
    }
    
    private String id_dokter;
    private String nama_dokter;
    private String status_dokter = "Aktif";
    private String nohp_dokter;
    private String jk_dokter = "Laki-Laki";
    private String username_dokter;
    private String password_dokter;
    private int tarif_dokter;
    private String status_crud;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane2 = new javax.swing.JOptionPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtidd = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtnamad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtnohpd = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cbjkd = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txttarifd = new javax.swing.JTextField();
        cbstatusd = new javax.swing.JComboBox<>();
        txtusernamed = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtpasswordd = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btntambah = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnsimpan = new javax.swing.JButton();
        btnbatal = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("ID Dokter");

        txtidd.setEnabled(false);
        txtidd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtiddActionPerformed(evt);
            }
        });
        txtidd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtiddKeyReleased(evt);
            }
        });

        jLabel2.setText("Nama Dokter");

        txtnamad.setEnabled(false);
        txtnamad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamadActionPerformed(evt);
            }
        });
        txtnamad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnamadKeyReleased(evt);
            }
        });

        jLabel3.setText("Status Dokter");

        jLabel4.setText("Harga Dokter");

        jLabel5.setText("Jenis Kelamin Dokter");

        txtnohpd.setEnabled(false);
        txtnohpd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnohpdActionPerformed(evt);
            }
        });
        txtnohpd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnohpdKeyReleased(evt);
            }
        });

        jLabel6.setText("Nohp Dokter");

        cbjkd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-Laki", "Perempuan" }));
        cbjkd.setEnabled(false);
        cbjkd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbjkdActionPerformed(evt);
            }
        });

        txttarifd.setEnabled(false);
        txttarifd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttarifdActionPerformed(evt);
            }
        });
        txttarifd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txttarifdKeyReleased(evt);
            }
        });

        cbstatusd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aktif", "Tidak Aktif" }));
        cbstatusd.setEnabled(false);
        cbstatusd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbstatusdActionPerformed(evt);
            }
        });

        txtusernamed.setToolTipText("");
        txtusernamed.setEnabled(false);
        txtusernamed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusernamedActionPerformed(evt);
            }
        });
        txtusernamed.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtusernamedKeyReleased(evt);
            }
        });

        jLabel8.setText("Username Dokter");

        jLabel9.setText("Password Dokter");

        txtpasswordd.setToolTipText("");
        txtpasswordd.setEnabled(false);
        txtpasswordd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpassworddActionPerformed(evt);
            }
        });
        txtpasswordd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpassworddKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8))
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtusernamed)
                            .addComponent(txtnamad)
                            .addComponent(cbstatusd, 0, 223, Short.MAX_VALUE)
                            .addComponent(txtidd, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtnohpd, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbjkd, javax.swing.GroupLayout.Alignment.LEADING, 0, 283, Short.MAX_VALUE)
                            .addComponent(txttarifd, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtpasswordd))))
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtidd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(cbjkd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtnamad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtnohpd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txttarifd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbstatusd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtusernamed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8)
                                .addComponent(txtpasswordd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(79, 79, 79)
                        .addComponent(jLabel7)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 11, 800, 180));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 860, 190));

        btntambah.setText("Tambah");
        btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahActionPerformed(evt);
            }
        });
        getContentPane().add(btntambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 120, 40));

        btnedit.setText("Edit");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });
        getContentPane().add(btnedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 120, 40));

        btndelete.setText("Delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 120, 40));

        btnsimpan.setText("Simpan");
        btnsimpan.setEnabled(false);
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });
        getContentPane().add(btnsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, 120, 40));

        btnbatal.setText("Batal");
        btnbatal.setEnabled(false);
        btnbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbatalActionPerformed(evt);
            }
        });
        getContentPane().add(btnbatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 210, 120, 40));

        btnreset.setText("Reset");
        btnreset.setEnabled(false);
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });
        getContentPane().add(btnreset, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 210, 120, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setIDD(String v) {
     id_dokter = v;
    }
    public void setNamaD(String v) {
     nama_dokter = v;
    }
    public void setUsernameD(String v) {
     username_dokter = v;
    }
    public void setPassD(String v) {
     password_dokter = v;
    }
    public void setNohpD(String v) {
     nohp_dokter = v;
    }
    public void setStatusD(String v) {
     status_dokter = v;
    }
    public void setHargaD(int v) {
     tarif_dokter = v;
    }
    public void setJKD(String v){
        jk_dokter = v;
    }
    public void setStatusC(String v) {
     status_crud = v;
    }
    public String getIDD() {
     return id_dokter;
    }
    public String getNamaD() {
     return nama_dokter;
    }
    public String getUsernameD() {
     return username_dokter;
    }
    public String getPassD() {
     return password_dokter;
    }
    public String getNohpD() {
     return nohp_dokter;
    }
    public String getStatusD() {
     return status_dokter;
    }
    public int getHargaD(){
        return tarif_dokter;
    }
    public String getJKD(){
        return jk_dokter;
    }
    public String getStatusC() {
     return status_crud;
    }
    
        //batal
    public void batal() {
     txtidd.setEnabled(false);
     txtnamad.setEnabled(false);
     txtnohpd.setEnabled(false);
     txtpasswordd.setEnabled(false);
     txtusernamed.setEnabled(false);
     cbstatusd.setEnabled(false);
     cbjkd.setEnabled(false);
     txttarifd.setEnabled(false);
     btnreset.setEnabled(false);
     btnbatal.setEnabled(false);
     btnsimpan.setEnabled(false);
     btndelete.setEnabled(true);
     btnedit.setEnabled(true);
     btntambah.setEnabled(true);
     setStatusC("");
     reset();
    }
    //reset
    public void reset() {
     txtidd.setText(null);
     txtnamad.setText(null);
     txtnohpd.setText(null);
     txtpasswordd.setText(null);
     txtusernamed.setText(null);
     txttarifd.setText(null);
     cbstatusd.setSelectedItem(this);
     cbjkd.setSelectedItem(this);
    }
    //Dipanggil Saat ingin mengenable semua text Field
    public void enableAllTF() {
     txtidd.setEnabled(true);
     txtnamad.setEnabled(true);
     txtnohpd.setEnabled(true);
     txtpasswordd.setEnabled(true);
     txtusernamed.setEnabled(true);
     cbstatusd.setEnabled(true);
     cbjkd.setEnabled(true);
     txttarifd.setEnabled(true);
    }
    public void insertData() {
        try {
            String sql = "INSERT INTO tabel_dokter VALUES ('"+getIDD()+"','"+getNamaD()+"','"+getJKD()+"','"+getHargaD()+"','"+getStatusD()+"','"+getNohpD()+"','"+getUsernameD()+"','"+getPassD()+"')";
            java.sql.Connection conn=(Connection)Koneksi.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Penyimpanan Data Berhasil");
            reset();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    public void updateData() {
           try {
            String sql ="UPDATE tabel_dokter SET nama_dokter = '"+getNamaD()+"', jk_dokter = '"+getJKD()+"',tarif_dokter= '"+getHargaD()+"',status_dokter= '"+getStatusD()+"',nohp_dokter= '"+getNohpD()+"',username= '"+getUsernameD()+"',password= '"+getPassD()+"' WHERE id_dokter = '"+getIDD()+"'";
            java.sql.Connection conn=(Connection)Koneksi.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "data berhasil di edit");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Perubahan Data Gagal"+e.getMessage());
        }
    }
    public void deleteData() {
            try {
            String sql ="DELETE FROM tabel_dokter where id_dokter='"+getIDD()+"'";
            java.sql.Connection conn=(Connection)Koneksi.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(this, "berhasil di hapus");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    public boolean verifikasiData(){
        if(getNamaD() == ""){
            JOptionPane.showMessageDialog(this, "Nama Dokter Masih Kosong");
            return false;
        }else if(getHargaD() == 0){
            JOptionPane.showMessageDialog(this, "Harga Dokter Masih Kosong");
            return false;
        }else if(getUsernameD() == ""){
            JOptionPane.showMessageDialog(this, "Username Dokter Masih Kosong");
            return false;
        }else if(getPassD() == ""){
            JOptionPane.showMessageDialog(this, "Password Dokter Masih Kosong");
            return false;
        }else if(getNohpD() == ""){
            JOptionPane.showMessageDialog(this, "Nomor HP Dokter Masih Kosong");
            return false;
        }else{
            return true;
        }
    }

    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
        btntambah.setEnabled(false);
        btndelete.setEnabled(false);
        btnedit.setEnabled(false);
        btnreset.setEnabled(true);
        btnbatal.setEnabled(true);
        btnsimpan.setEnabled(true);
        enableAllTF();
        setStatusC("tambah");
    }//GEN-LAST:event_btntambahActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        if (getStatusC() == "tambah") {
            if(verifikasiData() == true){
                insertData();
                load_table();
                batal();
            }
        } else if (getStatusC() == "edit") {
            if(verifikasiData() == true){
                updateData(); 
                load_table();
                batal();
            }
        } else if (getStatusC() == "hapus") {
            if(verifikasiData() == true){
                deleteData();  
                load_table();
                batal();
            }
        }
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        JOptionPane.showMessageDialog(null, "Silahkan Klik Data Yang Ingin Diedit Pada Tabel Dibawah");
        btntambah.setEnabled(false);
        btndelete.setEnabled(false);
        btnedit.setEnabled(false);
        btnreset.setEnabled(true);
        btnbatal.setEnabled(true);
        btnsimpan.setEnabled(true);
        enableAllTF();
        txtidd.setEnabled(false);
        setStatusC("edit");
    }//GEN-LAST:event_btneditActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        if(getStatusC() == "edit" || getStatusC() == "hapus"){
        int baris = jTable1.rowAtPoint(evt.getPoint());
        String id_pasien =jTable1.getValueAt(baris, 0).toString();
        txtidd.setText(id_pasien);
        setIDD(txtidd.getText());
        String nama_pasien =jTable1.getValueAt(baris, 1).toString();
        txtnamad.setText(nama_pasien);
        setNamaD(txtnamad.getText());
        String jr = jTable1.getValueAt(baris, 2).toString();
        cbjkd.setSelectedItem(jr);
        setJKD(cbjkd.getSelectedItem().toString());
        String tarif=jTable1.getValueAt(baris, 3).toString();
        txttarifd.setText(tarif);
        setHargaD(Integer.parseInt(txttarifd.getText()));
        String status = jTable1.getValueAt(baris, 4).toString();
        cbstatusd.setSelectedItem(status);
        setStatusD(cbstatusd.getSelectedItem().toString());
        String nohp = jTable1.getValueAt(baris, 5).toString();
        txtnohpd.setText(nohp);
        setNohpD(txtnohpd.getText());
        String username = jTable1.getValueAt(baris, 6).toString();
        txtusernamed.setText(username);
        setUsernameD(txtusernamed.getText());
        String password = jTable1.getValueAt(baris, 7).toString();
        txtpasswordd.setText(username);
        setPassD(txtpasswordd.getText());
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        JOptionPane.showMessageDialog(null, "Silahkan Klik Data Yang Ingin Dihapus Pada Tabel Dibawah, dan klik Delete Data");
        btntambah.setEnabled(false);
        btndelete.setEnabled(false);
        btnedit.setEnabled(false);
        btnreset.setEnabled(true);
        btnbatal.setEnabled(true);
        btnsimpan.setEnabled(true);
        btnsimpan.setText("Delete Data");
        txtidd.setEnabled(false);
        setStatusC("hapus");
    }//GEN-LAST:event_btndeleteActionPerformed

    private void txtiddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtiddActionPerformed
        setIDD(txtidd.getText());
    }//GEN-LAST:event_txtiddActionPerformed

    private void txtnamadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamadActionPerformed
        setNamaD(txtnamad.getText());
    }//GEN-LAST:event_txtnamadActionPerformed

    private void txtnohpdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnohpdActionPerformed
        setNohpD(txtnohpd.getText());
    }//GEN-LAST:event_txtnohpdActionPerformed

    private void txttarifdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttarifdActionPerformed
        setHargaD(Integer.parseInt(txttarifd.getText()));
    }//GEN-LAST:event_txttarifdActionPerformed

    private void cbstatusdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbstatusdActionPerformed
        setStatusD(cbstatusd.getSelectedItem().toString());
    }//GEN-LAST:event_cbstatusdActionPerformed

    private void cbjkdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbjkdActionPerformed
        setJKD(cbjkd.getSelectedItem().toString());
    }//GEN-LAST:event_cbjkdActionPerformed

    private void txtpassworddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpassworddActionPerformed
        setPassD(txtpasswordd.getText());
    }//GEN-LAST:event_txtpassworddActionPerformed

    private void txtusernamedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusernamedActionPerformed
        setUsernameD(txtusernamed.getText());
    }//GEN-LAST:event_txtusernamedActionPerformed

    private void btnbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbatalActionPerformed
        batal();
    }//GEN-LAST:event_btnbatalActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        reset();
    }//GEN-LAST:event_btnresetActionPerformed

    private void txtnamadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnamadKeyReleased
        setNamaD(txtnamad.getText());
    }//GEN-LAST:event_txtnamadKeyReleased

    private void txtusernamedKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtusernamedKeyReleased
        setUsernameD(txtusernamed.getText());
    }//GEN-LAST:event_txtusernamedKeyReleased

    private void txtnohpdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnohpdKeyReleased
        setNohpD(txtnohpd.getText());
    }//GEN-LAST:event_txtnohpdKeyReleased

    private void txttarifdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttarifdKeyReleased
        setHargaD(Integer.parseInt(txttarifd.getText()));
    }//GEN-LAST:event_txttarifdKeyReleased

    private void txtpassworddKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpassworddKeyReleased
        setPassD(txtpasswordd.getText());
    }//GEN-LAST:event_txtpassworddKeyReleased

    private void txtiddKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtiddKeyReleased
        setIDD(txtidd.getText());
    }//GEN-LAST:event_txtiddKeyReleased
private void load_table(){
        //menampilkan data database kedalam tabel
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID Dokter");
        model.addColumn("Nama Dokter");
        model.addColumn("Jenis Kelamin");
        model.addColumn("Tarif Dokter");
        model.addColumn("Status Dokter");
        model.addColumn("Nomor Telp");
        model.addColumn("Username Dokter");
        model.addColumn("Password Dokter");
        try {
            int no=1;
            String sql = "select * from tabel_dokter";
            java.sql.Connection conn=(Connection)Koneksi.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                model.addRow(new Object[]{res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(6),res.getString(7),res.getString(8)});
            }
            jTable1.setModel(model);
        } catch (Exception e) {
        }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageDokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageDokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageDokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageDokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageDokter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbatal;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnreset;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JButton btntambah;
    private javax.swing.JComboBox<String> cbjkd;
    private javax.swing.JComboBox<String> cbstatusd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JOptionPane jOptionPane2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtidd;
    private javax.swing.JTextField txtnamad;
    private javax.swing.JTextField txtnohpd;
    private javax.swing.JTextField txtpasswordd;
    private javax.swing.JTextField txttarifd;
    private javax.swing.JTextField txtusernamed;
    // End of variables declaration//GEN-END:variables
}
