/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.*; 
import java.awt.*; 
import java.awt.event.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.table.*;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import org.freixas.jcalendar.*;
public class ManagePemeriksaan extends javax.swing.JFrame {

    private String[] dataPopUp;
    /**
     * Creates new form ManagePasien
     */
    public ManagePemeriksaan() {
        initComponents();
        reset();
        load_table();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane2 = new javax.swing.JOptionPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtidpasien = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtnamapasien = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablepemeriksaan = new javax.swing.JTable();
        btntambah = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        btnsimpan = new javax.swing.JButton();
        btnbatal = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtiddokter = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtnamadokter = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cboxstatus = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtjam = new javax.swing.JSpinner(new SpinnerDateModel());
        txttanggal = new org.jdesktop.swingx.JXDatePicker();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Pasien"));

        jLabel1.setText("ID Pasien");

        txtidpasien.setEnabled(false);
        txtidpasien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtidpasienMousePressed(evt);
            }
        });
        txtidpasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidpasienActionPerformed(evt);
            }
        });

        jLabel2.setText("Nama Pasien");

        txtnamapasien.setEnabled(false);
        txtnamapasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamapasienActionPerformed(evt);
            }
        });

        jButton2.setText("Cari");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtnamapasien)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtidpasien, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2))
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(203, 203, 203)
                                .addComponent(jLabel7))
                            .addComponent(jLabel2))
                        .addGap(0, 10, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtidpasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(5, 5, 5)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtnamapasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(jLabel7))
        );

        tablepemeriksaan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablepemeriksaan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablepemeriksaanMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablepemeriksaan);

        btntambah.setText("Tambah");
        btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahActionPerformed(evt);
            }
        });

        btnedit.setText("Edit");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });

        btnhapus.setText("Delete");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        btnsimpan.setText("Simpan");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        btnbatal.setText("Batal");

        btnreset.setText("Reset");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Dokter"));

        jLabel8.setText("ID Dokter");

        txtiddokter.setEnabled(false);
        txtiddokter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtiddokterMouseClicked(evt);
            }
        });
        txtiddokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtiddokterActionPerformed(evt);
            }
        });

        jLabel9.setText("Nama Dokter");

        txtnamadokter.setEnabled(false);
        txtnamadokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamadokterActionPerformed(evt);
            }
        });

        jButton1.setText("Cari");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtnamadokter)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(203, 203, 203)
                                .addComponent(jLabel10))
                            .addComponent(jLabel9)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtiddokter, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtiddokter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(5, 5, 5)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtnamadokter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(jLabel10))
        );

        jLabel3.setText("Waktu Pemeriksaan");

        jLabel4.setText("Status");

        cboxstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pending", "On Process", "Waiting Payment", "Success", "Cancel" }));

        jLabel5.setText("ID Pemeriksaan");

        txtid.setEnabled(false);

        JSpinner.DateEditor timeEditor = new JSpinner.DateEditor(txtjam, "HH:mm:ss");
        txtjam.setEditor(timeEditor);
        // will only show the current time
        txtjam.setEnabled(false);

        txttanggal.setEnabled(false);
        txttanggal.setFormats(new String[]{"yyyy-MM-dd"});

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txttanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtjam, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(cboxstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(cboxstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(btntambah, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(btnedit, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(142, 142, 142)
                                .addComponent(btnsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(btnbatal, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(btnreset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 860, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 19, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btntambah, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnedit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbatal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnreset, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
        txtid.setEnabled(true);
        txttanggal.setEnabled(true);
        txtjam.setEnabled(true);
        cboxstatus.setEnabled(true);
        txtid.setText("");
        cboxstatus.setSelectedIndex(0);
        jButton1.setEnabled(true);
        jButton2.setEnabled(true);
        btntambah.setEnabled(false);
        btnhapus.setEnabled(false);
        btnedit.setEnabled(false);
        btnreset.setEnabled(true);
        btnbatal.setEnabled(true);
        btnsimpan.setEnabled(true);
        jLabel7.setText("tambah");
    }//GEN-LAST:event_btntambahActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        if(jLabel7.getText() == "tambah"){
        try {
            String sql = "INSERT INTO tabel_pemeriksaan(id_dokter,id_pasien,tanggal_pemeriksaan,status_pemeriksaan) VALUES ('"+txtiddokter.getText()+"','"+txtidpasien.getText()+"','"+Tanggalan()+"','"+cboxstatus.getSelectedItem()+"')";
            java.sql.Connection conn=(Connection)Koneksi.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Penyimpanan Data Berhasil");
            reset();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        }else if(jLabel7.getText() == "edit"){
           try {
            String sql ="UPDATE tabel_pemeriksaan SET id_dokter = '"+txtiddokter.getText()+"', id_pasien = '"+txtidpasien.getText()+"',tanggal_pemeriksaan = '"+Tanggalan()+"',status_pemeriksaaan= '"+cboxstatus.getSelectedItem()+"' WHERE kode_pemeriksaan = '"+txtid.getText()+"'";
            java.sql.Connection conn=(Connection)Koneksi.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "data berhasil di edit");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Perubahan Data Gagal"+e.getMessage());
        }
        }else if(jLabel7.getText() == "hapus"){
            try {
            String sql ="DELETE FROM tabel_pemeriksaan where kode_pemeriksaan='"+txtid.getText()+"'";
            java.sql.Connection conn=(Connection)Koneksi.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(this, "berhasil di hapus");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        }
        load_table();
        kosong();
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        JOptionPane.showMessageDialog(null, "Silahkan Klik Data Yang Ingin Diedit Pada Tabel Dibawah");
        txtid.setEnabled(true);
        txttanggal.setEnabled(true);
        txtjam.setEnabled(true);
        cboxstatus.setEnabled(true);
        jButton1.setEnabled(true);
        jButton2.setEnabled(true);
        btntambah.setEnabled(false);
        btnhapus.setEnabled(false);
        btnedit.setEnabled(false);
        btnreset.setEnabled(true);
        btnbatal.setEnabled(true);
        btnsimpan.setEnabled(true);
        jLabel7.setText("edit");
    }//GEN-LAST:event_btneditActionPerformed

    private void tablepemeriksaanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablepemeriksaanMouseClicked
        if(jLabel7.getText() == "edit" || jLabel7.getText() == "hapus"){
        int baris = tablepemeriksaan.rowAtPoint(evt.getPoint());
        String kode_pemeriksaaan =tablepemeriksaan.getValueAt(baris, 0).toString();
        txtid.setText(kode_pemeriksaaan);
        String id_pasien =tablepemeriksaan.getValueAt(baris, 6).toString();
        txtidpasien.setText(id_pasien);
        String id_dokter =tablepemeriksaan.getValueAt(baris, 5).toString();
        txtiddokter.setText(id_dokter);
        String nama_dokter = tablepemeriksaan.getValueAt(baris, 1).toString();
        txtnamadokter.setText(nama_dokter);
        String nama_pasien = tablepemeriksaan.getValueAt(baris, 2).toString();
        txtnamapasien.setText(nama_dokter);
        String status_pemeriksaan =tablepemeriksaan.getValueAt(baris, 4).toString();
        cboxstatus.setSelectedItem(status_pemeriksaan);
        }
    }//GEN-LAST:event_tablepemeriksaanMouseClicked

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        JOptionPane.showMessageDialog(null, "Silahkan Klik Data Yang Ingin Dihapus Pada Tabel Dibawah, dan klik Delete Data");
        btntambah.setEnabled(false);
        btnhapus.setEnabled(false);
        btnedit.setEnabled(false);
        btnreset.setEnabled(true);
        btnbatal.setEnabled(true);
        btnsimpan.setEnabled(true);
        btnsimpan.setText("Delete Data");
        jLabel7.setText("hapus");
    }//GEN-LAST:event_btnhapusActionPerformed

    private void txtnamapasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamapasienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamapasienActionPerformed

    private void txtidpasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidpasienActionPerformed

    }//GEN-LAST:event_txtidpasienActionPerformed

    private void txtiddokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtiddokterActionPerformed

    }//GEN-LAST:event_txtiddokterActionPerformed

    private void txtnamadokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamadokterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamadokterActionPerformed

    private void txtiddokterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtiddokterMouseClicked


    }//GEN-LAST:event_txtiddokterMouseClicked

    private void txtidpasienMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtidpasienMousePressed

    }//GEN-LAST:event_txtidpasienMousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        PemeriksaanDokter pd = new PemeriksaanDokter(new javax.swing.JFrame(), true);
        pd.setVisible(true);
        txtiddokter.setText(pd.getAmbilData()[0]);
        txtnamadokter.setText(pd.getAmbilData()[1]);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       PemeriksaanPasien pp = new PemeriksaanPasien(new javax.swing.JFrame(), true);
        pp.setVisible(true);
        txtidpasien.setText(pp.getAmbilData()[0]);
        txtnamapasien.setText(pp.getAmbilData()[1]);
    }//GEN-LAST:event_jButton2ActionPerformed
private void load_table(){
        //menampilkan data database kedalam tabel
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID Pemeriksaan");
        model.addColumn("Nama Dokter");
        model.addColumn("Nama Pasien");
        model.addColumn("Tanggal Pemeriksaan");
        model.addColumn("Status Pemeriksaan");
        model.addColumn("ID Dokter");
        model.addColumn("ID Pasien");
        try {
            int no=1;
            String sql = "select p.kode_pemeriksaan,d.nama_dokter,pa.nama_pasien,p.tanggal_pemeriksaan,p.status_pemeriksaan,p.id_dokter,p.id_pasien from tabel_pemeriksaan p INNER JOIN tabel_dokter d ON p.id_dokter = d.id_dokter INNER JOIN tabel_pasien pa ON pa.id_pasien = p.id_pasien";
            java.sql.Connection conn=(Connection)Koneksi.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                model.addRow(new Object[]{res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(6),res.getString(7)});
            }
            tablepemeriksaan.setModel(model);
        } catch (Exception e) {
        }
        //Hide Kolom
        tablepemeriksaan.getColumnModel().getColumn(5).setWidth(0);
        tablepemeriksaan.getColumnModel().getColumn(5).setMinWidth(0);
        tablepemeriksaan.getColumnModel().getColumn(5).setMaxWidth(0); 
        tablepemeriksaan.getColumnModel().getColumn(6).setWidth(0);
        tablepemeriksaan.getColumnModel().getColumn(6).setMinWidth(0);
        tablepemeriksaan.getColumnModel().getColumn(6).setMaxWidth(0); 
}
private String Tanggalan(){
    DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
txttanggal.setFormats(dateFormat);
DateFormat sysDate = new SimpleDateFormat("yyyy/MM/dd");
JSpinner.DateEditor timeEditor = new JSpinner.DateEditor(txtjam, "HH:mm:ss");
txtjam.setEditor(timeEditor);
String date_to_store = sysDate.format(txttanggal.getDate()).toString()+" "+timeEditor.getFormat().format(txtjam.getValue());
return date_to_store;
}
public void setDataPopUp(String[] dataPopUp)
{
this.dataPopUp = dataPopUp;
}
	
public String[] getDataPopUp()
{
return dataPopUp;
}
private void reset(){
    txtidpasien.setEnabled(false);
    txtnamapasien.setEnabled(false);
    cboxstatus.setEnabled(false);
    btnreset.setEnabled(false);
    btnbatal.setEnabled(false);
    btnsimpan.setEnabled(false);
    btnhapus.setEnabled(true);
    btnedit.setEnabled(true);
    btntambah.setEnabled(true);

}
private void kosong(){
        txtid.setEnabled(false);
        txttanggal.setEnabled(false);
        txtjam.setEnabled(false);
        cboxstatus.setEnabled(false);
        txtid.setText("");
        cboxstatus.setSelectedItem(this);
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        btntambah.setEnabled(true);
        btnhapus.setEnabled(true);
        btnedit.setEnabled(true);
        btnreset.setEnabled(false);
        btnbatal.setEnabled(false);
        btnsimpan.setEnabled(false);
        jLabel7.setText("tambah");
}
  /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagePemeriksaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagePemeriksaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagePemeriksaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagePemeriksaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagePemeriksaan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbatal;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnreset;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JButton btntambah;
    private javax.swing.JComboBox<String> cboxstatus;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JOptionPane jOptionPane2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablepemeriksaan;
    private javax.swing.JTextField txtid;
    public javax.swing.JTextField txtiddokter;
    public javax.swing.JTextField txtidpasien;
    private javax.swing.JSpinner txtjam;
    public javax.swing.JTextField txtnamadokter;
    public javax.swing.JTextField txtnamapasien;
    private org.jdesktop.swingx.JXDatePicker txttanggal;
    // End of variables declaration//GEN-END:variables
}
